### PR TITLE
Skin limit bypass, add missing skins

### PR DESCRIPTION
**Pull request by AbyssMorgan**

### CODE REVIEW

**Comment by IstuntmanI** [comment]
Look at SWFOPRO too ... oh god why.

**Comment by AbyssMorgan** [comment]
Game don't need to remove any skins.

**Comment by IstuntmanI** [comment]
I didn't say that. I said that those skins are probably unused by the game and SA:MP too and maybe could be added too. Too much nude skins. XD

**Comment by AbyssMorgan** [comment]
Current nude skins 1, second need fix with SAMP.img but my friend say: there are 6 nude skins in gta sa xD

**Pull request merged**
